### ISSUE TITLE
Using your plugin as snippet manager ?

### ISSUE THREAD

**Issue by StatelessCat** [pbihler/atom-macros#1]
Hey,
Maybe it's obvious, but is it possible to use your plugin to define snippets and associate them to a key or command ?

#### for example, i want to create a snippet for 
```xml
<xsd:element name="%s">
```
and to bind this on a key to put the snippet on my document and move the cursor on %s 

Thanks :)

**Comment by StatelessCat** [comment]
Sorry, I just found out what I wanted already exists in Atom https://atom.io/packages/snippets

**Comment by pbihler** [comment]
Yes, that plugin explicetly manages snippets.

If you defined your snippet like
```cson
  'xsd':
    'prefix':'<xsd'
    'body':'<xsd:element name="${1:name}">'
```

you can define a macro like:
```coffeescript
@xsdElement = ->
  getActiveTextEditor().getCursors()[0].selection.insertText '<xsd'
  dispatchEditorCommand 'snippets:expand'
```
to put a button for the snippet in the toolbar, or assign a shortcut in the keymap to `macros:xsdElement`.
