### ISSUE TITLE
Need some kind of wiki for people to share their macros.

### ISSUE THREAD

**Issue by robru** [pbihler/atom-macros#2]
Hi, I noticed this project doesn't have a wiki, at least not on this github project. Is there one somewhere else?

I'm curious how other people are using these macros and would even like to share some of my own.

Thanks!

**Comment by pbihler** [comment]
Here you go: https://github.com/pbihler/atom-macros/wiki

**Comment by ryanjones** [comment]
I've added a quick text injection macro here:
https://github.com/pbihler/atom-macros/wiki#typing-macro

(I use it for entering 'binding.pry' in a ruby script.)
